on: [pull_request, workflow_dispatch]

name: Continuous integration

jobs:
  fmt:
    name: Rustfmt
    runs-on: core 
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - run: cargo fmt --all -- --check

  analyze:
    name: Dusk Analyzer
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - run: cargo install --git https://github.com/dusk-network/cargo-dusk-analyzer
      - run: cargo dusk-analyzer

  test_nightly-linux:
    name: "[Linux] Nightly tests"
    runs-on: core 
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - run: cargo test --release
      - run: cargo clippy --all-features --release -- -D warnings

  test_nightly-macintel:
    name: "[Mac Intel] Nightly tests"
    runs-on: macos-latest 
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1

      - name: Add arm target for Apple Silicon build
        run: rustup target add aarch64-apple-darwin 

      - run: cargo test

  test_nightly-macm1:
    name: "[Mac arm64] Nightly checks"
    runs-on: macos-latest 
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1

      - name: Add arm target for Apple Silicon build
        run: rustup target add aarch64-apple-darwin 

      - run: cargo check --target=aarch64-apple-darwin

  test_nightly-win:
    name: "[Windows] Nightly tests"
    runs-on: windows-latest 
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1

      - run: cargo test
